version: "3.7"

services:
  authenticate-db:
    image: mongo
    container_name: authenticate-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mss-authenticate/data:/var/lib/mongodb
    
  mss-authenticate-api:
    build:
      context: "./mss-authenticate"
      dockerfile: Dockerfile
    container_name: mss-authenticate-api
    restart: always
    volumes:
      - ./mss-authenticate/data:/home/node/app
    ports:
      - "3200:8080"
    depends_on:
      - authenticate-db
      - rabbitmq
    environment:
      PORT: 8080
      CONNECTIONSTRING: mongodb://root:123456@authenticate-db:27017/authenticate_db?authSource=admin
      RABBITMQ: amqp://admin:admin@rabbitmq:5672    
      API_JWKSURI: http://mss-authenticate-api:8080/.well-known/jwks.json
  
  user-db:
    image: mongo
    container_name: user-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mss-user/data:/var/lib/mongodb
    
  mss-user-api:
    build:
      context: "./mss-user"
      dockerfile: Dockerfile
    container_name: mss-user-api
    restart: always
    volumes:
      - ./mss-user/data:/home/node/app
    ports:
      - "3100:8080"
    depends_on:
      - user-db
      - mss-authenticate-api
      - rabbitmq
    environment:
      PORT: 8080
      API_JWKSURI: http://mss-authenticate-api:8080/.well-known/jwks.json
      CONNECTIONSTRING: mongodb://root:123456@user-db:27017/user_db?authSource=admin
      RABBITMQ: amqp://admin:admin@rabbitmq:5672
      
  haven-db:
    image: mongo
    container_name: haven-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mss-haven/data:/var/lib/mongodb
    
  mss-haven-api:
    build:
      context: "./mss-haven"
      dockerfile: Dockerfile
    container_name: mss-haven-api
    restart: always
    volumes:
      - ./mss-haven/data:/home/node/app
    ports:
      - "3300:8080"
    depends_on:
      - haven-db
      - mss-authenticate-api
    environment:
      PORT: 8080
      API_JWKSURI: http://mss-authenticate-api:8080/.well-known/jwks.json
      CONNECTIONSTRING: mongodb://root:123456@haven-db:27017/haven_db?authSource=admin

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

      
    
  

