apiVersion: v1
kind: Service
metadata:
  labels:
    app: authenticate-db
  name: authenticate-db-service
spec:
  ports:
  - port: 27017
    targetPort: port-auth-db
  selector:
    app: authenticate-db
