apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: haven-db
  name: haven-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haven-db
  template:
    metadata:
      labels:
        app: haven-db
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
      - image: mongo
        name: haven-db
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: '123456'
        ports:
        - containerPort: 27017
          name: port-haven-db
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always